-- Generated by etl/export_region_registry_sql.py from etl/region_registry.json.
-- Do not edit by hand: change the registry and regenerate.
-- registry version: region-registry-v1 (2026-09-20)
--
-- Replaces the literal three-region CHECK constraints from migration 06 with a
-- reference table and foreign keys. Promoting a region during a nationwide wave
-- is then an UPDATE of is_production, not a new migration.
--
-- Idempotent: safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS region_registry (
    canonical_name TEXT PRIMARY KEY,
    short_name TEXT NOT NULL,
    legal_dong_code TEXT NOT NULL UNIQUE,
    legacy_legal_dong_codes TEXT[] NOT NULL DEFAULT '{}',
    neis_office_code TEXT NOT NULL UNIQUE,
    education_office TEXT NOT NULL UNIQUE,
    address_prefixes TEXT[] NOT NULL,
    has_city_level BOOLEAN NOT NULL,
    is_production BOOLEAN NOT NULL DEFAULT FALSE,
    wave TEXT NOT NULL,
    registry_version TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE region_registry IS
    'First-level administrative regions. Mirrors etl/region_registry.json; regenerate migrations with etl/export_region_registry_sql.py.';

INSERT INTO region_registry (
    canonical_name, short_name, legal_dong_code, legacy_legal_dong_codes,
    neis_office_code, education_office, address_prefixes, has_city_level,
    is_production, wave, registry_version
)
SELECT
    seed.canonical_name, seed.short_name, seed.legal_dong_code, seed.legacy_legal_dong_codes,
    seed.neis_office_code, seed.education_office, seed.address_prefixes, seed.has_city_level,
    seed.is_production, seed.wave, 'region-registry-v1'
FROM (VALUES
    ('서울특별시', '서울', '11', ARRAY[]::TEXT[], 'B10', '서울특별시교육청', ARRAY['서울특별시']::TEXT[], FALSE, TRUE, 'capital'),
    ('경기도', '경기', '41', ARRAY[]::TEXT[], 'J10', '경기도교육청', ARRAY['경기도']::TEXT[], TRUE, TRUE, 'capital'),
    ('인천광역시', '인천', '28', ARRAY[]::TEXT[], 'E10', '인천광역시교육청', ARRAY['인천광역시']::TEXT[], FALSE, TRUE, 'capital'),
    ('부산광역시', '부산', '26', ARRAY[]::TEXT[], 'C10', '부산광역시교육청', ARRAY['부산광역시']::TEXT[], FALSE, FALSE, 'N1'),
    ('대구광역시', '대구', '27', ARRAY[]::TEXT[], 'D10', '대구광역시교육청', ARRAY['대구광역시']::TEXT[], FALSE, FALSE, 'N1'),
    ('대전광역시', '대전', '30', ARRAY[]::TEXT[], 'G10', '대전광역시교육청', ARRAY['대전광역시']::TEXT[], FALSE, FALSE, 'N1'),
    ('광주광역시', '광주', '29', ARRAY[]::TEXT[], 'F10', '광주광역시교육청', ARRAY['광주광역시']::TEXT[], FALSE, FALSE, 'N1'),
    ('울산광역시', '울산', '31', ARRAY[]::TEXT[], 'H10', '울산광역시교육청', ARRAY['울산광역시']::TEXT[], FALSE, FALSE, 'N1'),
    ('전라남도', '전남', '46', ARRAY[]::TEXT[], 'Q10', '전라남도교육청', ARRAY['전라남도']::TEXT[], TRUE, FALSE, 'N1'),
    ('세종특별자치시', '세종', '36', ARRAY[]::TEXT[], 'I10', '세종특별자치시교육청', ARRAY['세종특별자치시']::TEXT[], FALSE, FALSE, 'N2'),
    ('제주특별자치도', '제주', '50', ARRAY[]::TEXT[], 'T10', '제주특별자치도교육청', ARRAY['제주특별자치도']::TEXT[], TRUE, FALSE, 'N2'),
    ('강원특별자치도', '강원', '51', ARRAY['42']::TEXT[], 'K10', '강원특별자치도교육청', ARRAY['강원특별자치도', '강원도']::TEXT[], TRUE, FALSE, 'N2'),
    ('충청북도', '충북', '43', ARRAY[]::TEXT[], 'M10', '충청북도교육청', ARRAY['충청북도']::TEXT[], TRUE, FALSE, 'N2'),
    ('충청남도', '충남', '44', ARRAY[]::TEXT[], 'N10', '충청남도교육청', ARRAY['충청남도']::TEXT[], TRUE, FALSE, 'N2'),
    ('전북특별자치도', '전북', '52', ARRAY['45']::TEXT[], 'P10', '전북특별자치도교육청', ARRAY['전북특별자치도', '전라북도']::TEXT[], TRUE, FALSE, 'N2'),
    ('경상북도', '경북', '47', ARRAY[]::TEXT[], 'R10', '경상북도교육청', ARRAY['경상북도']::TEXT[], TRUE, FALSE, 'N2'),
    ('경상남도', '경남', '48', ARRAY[]::TEXT[], 'S10', '경상남도교육청', ARRAY['경상남도']::TEXT[], TRUE, FALSE, 'N2')
) AS seed (
    canonical_name, short_name, legal_dong_code, legacy_legal_dong_codes,
    neis_office_code, education_office, address_prefixes, has_city_level,
    is_production, wave
)
ON CONFLICT (canonical_name) DO UPDATE
SET short_name = EXCLUDED.short_name,
    legal_dong_code = EXCLUDED.legal_dong_code,
    legacy_legal_dong_codes = EXCLUDED.legacy_legal_dong_codes,
    neis_office_code = EXCLUDED.neis_office_code,
    education_office = EXCLUDED.education_office,
    address_prefixes = EXCLUDED.address_prefixes,
    has_city_level = EXCLUDED.has_city_level,
    is_production = EXCLUDED.is_production,
    wave = EXCLUDED.wave,
    registry_version = EXCLUDED.registry_version,
    updated_at = NOW();

-- Region lookup from an address, including pre-rename prefixes such as 강원도.
-- The longest matching prefix wins, so a province name never loses to a shorter one.
CREATE OR REPLACE FUNCTION region_from_address(address TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
    SELECT registry.canonical_name
    FROM region_registry AS registry,
         LATERAL UNNEST(registry.address_prefixes) AS prefix
    WHERE address LIKE prefix || ' %'
    ORDER BY LENGTH(prefix) DESC
    LIMIT 1;
$$;

-- Replace migration 06's literal region checks with registry-backed foreign keys.
ALTER TABLE apartment_complex_master DROP CONSTRAINT IF EXISTS apartment_complex_region_check;
ALTER TABLE apartment_assignment_units DROP CONSTRAINT IF EXISTS apartment_assignment_region_check;

ALTER TABLE apartment_complex_master DROP CONSTRAINT IF EXISTS apartment_complex_region_fkey;
ALTER TABLE apartment_complex_master
    ADD CONSTRAINT apartment_complex_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

ALTER TABLE apartment_assignment_units DROP CONSTRAINT IF EXISTS apartment_assignment_region_fkey;
ALTER TABLE apartment_assignment_units
    ADD CONSTRAINT apartment_assignment_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

-- school_master.region had no validation at all before this.
ALTER TABLE school_master DROP CONSTRAINT IF EXISTS school_master_region_fkey;
ALTER TABLE school_master
    ADD CONSTRAINT school_master_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

-- Keep the monitoring schedules aligned with whatever is in production.
-- Guarded so this migration also applies to a database without migration 12.
DO $$
BEGIN
    IF TO_REGCLASS('public.etl_schedules') IS NOT NULL THEN
        UPDATE etl_schedules
        SET scope_regions = (
            SELECT COALESCE(JSONB_AGG(canonical_name ORDER BY canonical_name), '[]'::JSONB)
            FROM region_registry
            WHERE is_production
        );
    END IF;
END $$;

-- Private like every other control table: the public contract stays at
-- school_master and school_apartment_serving.
ALTER TABLE region_registry ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE region_registry FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE region_registry TO service_role;
REVOKE ALL ON FUNCTION region_from_address(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION region_from_address(TEXT) TO service_role;

COMMIT;
