// Generated by etl/export_region_registry_ts.py from etl/region_registry.json.
// Do not edit by hand: change the registry and regenerate.
// registry version: region-registry-v1 (2026-09-20)

export interface RegionDefinition {
  canonicalName: string
  shortName: string
  hasCityLevel: boolean
  isProduction: boolean
  center: { lat: number; lng: number }
  bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number }
}

export const REGIONS: RegionDefinition[] = [
  {
    canonicalName: '서울특별시',
    shortName: '서울',
    hasCityLevel: false,
    isProduction: true,
    center: { lat: 37.5665, lng: 126.978 },
    bounds: { minLat: 37.3914, maxLat: 37.7372, minLng: 126.7546, maxLng: 127.2303 },
  },
  {
    canonicalName: '경기도',
    shortName: '경기',
    hasCityLevel: true,
    isProduction: true,
    center: { lat: 37.4138, lng: 127.5183 },
    bounds: { minLat: 36.87, maxLat: 38.233, minLng: 126.5022, maxLng: 127.8011 },
  },
  {
    canonicalName: '인천광역시',
    shortName: '인천',
    hasCityLevel: false,
    isProduction: true,
    center: { lat: 37.4563, lng: 126.7052 },
    bounds: { minLat: 37.1268, maxLat: 38.0254, minLng: 124.6116, maxLng: 126.8304 },
  },
  {
    canonicalName: '부산광역시',
    shortName: '부산',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 35.2054, lng: 129.0569 },
    bounds: { minLat: 35.0011, maxLat: 35.4097, minLng: 128.7813, maxLng: 129.3325 },
  },
  {
    canonicalName: '대구광역시',
    shortName: '대구',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 35.957, lng: 128.5829 },
    bounds: { minLat: 35.6098, maxLat: 36.3043, minLng: 128.3626, maxLng: 128.8033 },
  },
  {
    canonicalName: '대전광역시',
    shortName: '대전',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 36.3417, lng: 127.379 },
    bounds: { minLat: 36.1792, maxLat: 36.5042, minLng: 127.2142, maxLng: 127.5438 },
  },
  {
    canonicalName: '광주광역시',
    shortName: '광주',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 35.1566, lng: 126.8515 },
    bounds: { minLat: 35.0167, maxLat: 35.2965, minLng: 126.6509, maxLng: 127.0521 },
  },
  {
    canonicalName: '울산광역시',
    shortName: '울산',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 35.5109, lng: 129.2715 },
    bounds: { minLat: 35.3011, maxLat: 35.7207, minLng: 129.0361, maxLng: 129.5069 },
  },
  {
    canonicalName: '전라남도',
    shortName: '전남',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 34.7433, lng: 126.4541 },
    bounds: { minLat: 34.0026, maxLat: 35.4841, minLng: 125.0803, maxLng: 127.828 },
  },
  {
    canonicalName: '세종특별자치시',
    shortName: '세종',
    hasCityLevel: false,
    isProduction: false,
    center: { lat: 36.5821, lng: 127.2625 },
    bounds: { minLat: 36.3937, maxLat: 36.7706, minLng: 127.1084, maxLng: 127.4166 },
  },
  {
    canonicalName: '제주특별자치도',
    shortName: '제주',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 33.5667, lng: 126.5661 },
    bounds: { minLat: 33.1192, maxLat: 34.0143, minLng: 126.1269, maxLng: 127.0054 },
  },
  {
    canonicalName: '강원특별자치도',
    shortName: '강원',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 37.7973, lng: 128.2535 },
    bounds: { minLat: 37.0476, maxLat: 38.547, minLng: 127.1148, maxLng: 129.3922 },
  },
  {
    canonicalName: '충청북도',
    shortName: '충북',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 36.6041, lng: 127.8843 },
    bounds: { minLat: 35.9736, maxLat: 37.2346, minLng: 127.2361, maxLng: 128.5326 },
  },
  {
    canonicalName: '충청남도',
    shortName: '충남',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 36.531, lng: 126.8265 },
    bounds: { minLat: 35.9634, maxLat: 37.0985, minLng: 126.0317, maxLng: 127.6213 },
  },
  {
    canonicalName: '전북특별자치도',
    shortName: '전북',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 35.7375, lng: 127.0703 },
    bounds: { minLat: 35.2786, maxLat: 36.1965, minLng: 126.2423, maxLng: 127.8984 },
  },
  {
    canonicalName: '경상북도',
    shortName: '경북',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 36.5549, lng: 129.3945 },
    bounds: { minLat: 35.5231, maxLat: 37.5867, minLng: 127.8361, maxLng: 130.9528 },
  },
  {
    canonicalName: '경상남도',
    shortName: '경남',
    hasCityLevel: true,
    isProduction: false,
    center: { lat: 35.2369, lng: 128.4009 },
    bounds: { minLat: 34.5855, maxLat: 35.8883, minLng: 127.5783, maxLng: 129.2236 },
  },
]

export const PRODUCTION_REGION_NAMES: string[] = REGIONS.filter(
  (region) => region.isProduction,
).map((region) => region.canonicalName)

const BY_NAME = new Map(REGIONS.map((region) => [region.canonicalName, region]))

export const findRegion = (name: string): RegionDefinition | undefined =>
  BY_NAME.get(name.trim())

/**
 * Whether addresses in this region carry a city level between region and
 * district. Every province does; the metropolitan cities and Sejong do not.
 */
export const regionHasCityLevel = (name: string): boolean =>
  findRegion(name)?.hasCityLevel ?? false

export const regionCenter = (name: string): { lat: number; lng: number } | undefined =>
  findRegion(name)?.center
