#!/usr/bin/env python3
"""Generate the region-registry database migration from the region registry.

The migration replaces the literal three-region CHECK constraints with a
reference table and foreign keys, so adding a region during a nationwide wave
becomes a data change rather than another schema migration.

    python etl/export_region_registry_sql.py            # write the migration
    python etl/export_region_registry_sql.py --check    # fail if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in (None, ""):  # `python etl/export_region_registry_sql.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from etl.region_registry import load_registry

TARGET = Path(__file__).resolve().parents[1] / "sql" / "16_create_region_registry_contract.sql"


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def text_array(values) -> str:
    return "ARRAY[" + ", ".join(quote(value) for value in values) + "]::TEXT[]"


def render() -> str:
    registry = load_registry()
    rows = []
    for region in registry:
        rows.append(
            "    ("
            f"{quote(region.canonical_name)}, {quote(region.short_name)}, "
            f"{quote(region.legal_dong_code)}, {text_array(region.legacy_legal_dong_codes)}, "
            f"{quote(region.neis_office_code)}, {quote(region.education_office)}, "
            f"{text_array(region.address_prefixes)}, "
            f"{'TRUE' if region.has_city_level else 'FALSE'}, "
            f"{'TRUE' if region.is_production else 'FALSE'}, "
            f"{quote(region.wave)})"
        )
    values = ",\n".join(rows)

    return f"""-- Generated by etl/export_region_registry_sql.py from etl/region_registry.json.
-- Do not edit by hand: change the registry and regenerate.
-- registry version: {registry.registry_version} ({registry.updated})
--
-- Replaces the literal three-region CHECK constraints from migration 06 with a
-- reference table and foreign keys. Promoting a region during a nationwide wave
-- is then an UPDATE of is_production, not a new migration.
--
-- Idempotent: safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS region_registry (
    canonical_name TEXT PRIMARY KEY,
    short_name TEXT NOT NULL,
    legal_dong_code TEXT NOT NULL UNIQUE,
    legacy_legal_dong_codes TEXT[] NOT NULL DEFAULT '{{}}',
    neis_office_code TEXT NOT NULL UNIQUE,
    education_office TEXT NOT NULL UNIQUE,
    address_prefixes TEXT[] NOT NULL,
    has_city_level BOOLEAN NOT NULL,
    is_production BOOLEAN NOT NULL DEFAULT FALSE,
    wave TEXT NOT NULL,
    registry_version TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE region_registry IS
    'First-level administrative regions. Mirrors etl/region_registry.json; regenerate migrations with etl/export_region_registry_sql.py.';

INSERT INTO region_registry (
    canonical_name, short_name, legal_dong_code, legacy_legal_dong_codes,
    neis_office_code, education_office, address_prefixes, has_city_level,
    is_production, wave, registry_version
)
SELECT
    seed.canonical_name, seed.short_name, seed.legal_dong_code, seed.legacy_legal_dong_codes,
    seed.neis_office_code, seed.education_office, seed.address_prefixes, seed.has_city_level,
    seed.is_production, seed.wave, {quote(registry.registry_version)}
FROM (VALUES
{values}
) AS seed (
    canonical_name, short_name, legal_dong_code, legacy_legal_dong_codes,
    neis_office_code, education_office, address_prefixes, has_city_level,
    is_production, wave
)
ON CONFLICT (canonical_name) DO UPDATE
SET short_name = EXCLUDED.short_name,
    legal_dong_code = EXCLUDED.legal_dong_code,
    legacy_legal_dong_codes = EXCLUDED.legacy_legal_dong_codes,
    neis_office_code = EXCLUDED.neis_office_code,
    education_office = EXCLUDED.education_office,
    address_prefixes = EXCLUDED.address_prefixes,
    has_city_level = EXCLUDED.has_city_level,
    is_production = EXCLUDED.is_production,
    wave = EXCLUDED.wave,
    registry_version = EXCLUDED.registry_version,
    updated_at = NOW();

-- Region lookup from an address, including pre-rename prefixes such as 강원도.
-- The longest matching prefix wins, so a province name never loses to a shorter one.
CREATE OR REPLACE FUNCTION region_from_address(address TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
    SELECT registry.canonical_name
    FROM region_registry AS registry,
         LATERAL UNNEST(registry.address_prefixes) AS prefix
    WHERE address LIKE prefix || ' %'
    ORDER BY LENGTH(prefix) DESC
    LIMIT 1;
$$;

-- Replace migration 06's literal region checks with registry-backed foreign keys.
ALTER TABLE apartment_complex_master DROP CONSTRAINT IF EXISTS apartment_complex_region_check;
ALTER TABLE apartment_assignment_units DROP CONSTRAINT IF EXISTS apartment_assignment_region_check;

ALTER TABLE apartment_complex_master DROP CONSTRAINT IF EXISTS apartment_complex_region_fkey;
ALTER TABLE apartment_complex_master
    ADD CONSTRAINT apartment_complex_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

ALTER TABLE apartment_assignment_units DROP CONSTRAINT IF EXISTS apartment_assignment_region_fkey;
ALTER TABLE apartment_assignment_units
    ADD CONSTRAINT apartment_assignment_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

-- school_master.region had no validation at all before this.
ALTER TABLE school_master DROP CONSTRAINT IF EXISTS school_master_region_fkey;
ALTER TABLE school_master
    ADD CONSTRAINT school_master_region_fkey
    FOREIGN KEY (region) REFERENCES region_registry(canonical_name) ON UPDATE CASCADE;

-- Keep the monitoring schedules aligned with whatever is in production.
-- Guarded so this migration also applies to a database without migration 12.
DO $$
BEGIN
    IF TO_REGCLASS('public.etl_schedules') IS NOT NULL THEN
        UPDATE etl_schedules
        SET scope_regions = (
            SELECT COALESCE(JSONB_AGG(canonical_name ORDER BY canonical_name), '[]'::JSONB)
            FROM region_registry
            WHERE is_production
        );
    END IF;
END $$;

-- Private like every other control table: the public contract stays at
-- school_master and school_apartment_serving.
ALTER TABLE region_registry ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE region_registry FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE region_registry TO service_role;
REVOKE ALL ON FUNCTION region_from_address(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION region_from_address(TEXT) TO service_role;

COMMIT;
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the migration is out of date")
    args = parser.parse_args(argv)

    rendered = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != rendered:
            print(f"{TARGET} is out of date; run python etl/export_region_registry_sql.py")
            return 1
        print(f"{TARGET.name} is current")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
