#!/usr/bin/env python3
"""Generate the frontend's region constants from the region registry.

`etl/region_registry.json` is the single source of truth, but it sits outside
`tsconfig`'s `src` include, so the frontend reads a generated TypeScript module
instead of importing the JSON. Regenerate after editing the registry:

    python etl/export_region_registry_ts.py

`--check` verifies the generated file is current without writing, which is what
the drift test runs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ in (None, ""):  # `python etl/export_region_registry_ts.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from etl.region_registry import load_registry

TARGET = Path(__file__).resolve().parents[1] / "src" / "constants" / "regionRegistry.ts"


def render() -> str:
    registry = load_registry()
    lines = [
        "// Generated by etl/export_region_registry_ts.py from etl/region_registry.json.",
        "// Do not edit by hand: change the registry and regenerate.",
        f"// registry version: {registry.registry_version} ({registry.updated})",
        "",
        "export interface RegionDefinition {",
        "  canonicalName: string",
        "  shortName: string",
        "  hasCityLevel: boolean",
        "  isProduction: boolean",
        "  center: { lat: number; lng: number }",
        "  bounds: { minLat: number; maxLat: number; minLng: number; maxLng: number }",
        "}",
        "",
        "export const REGIONS: RegionDefinition[] = [",
    ]
    for region in registry:
        bounds = region.bounds
        center_lat, center_lng = region.center
        lines.extend(
            [
                "  {",
                f"    canonicalName: '{region.canonical_name}',",
                f"    shortName: '{region.short_name}',",
                f"    hasCityLevel: {'true' if region.has_city_level else 'false'},",
                f"    isProduction: {'true' if region.is_production else 'false'},",
                f"    center: {{ lat: {center_lat}, lng: {center_lng} }},",
                "    bounds: {"
                f" minLat: {bounds.min_lat}, maxLat: {bounds.max_lat},"
                f" minLng: {bounds.min_lng}, maxLng: {bounds.max_lng} }},",
                "  },",
            ]
        )
    lines.extend(
        [
            "]",
            "",
            "export const PRODUCTION_REGION_NAMES: string[] = REGIONS.filter(",
            "  (region) => region.isProduction,",
            ").map((region) => region.canonicalName)",
            "",
            "const BY_NAME = new Map(REGIONS.map((region) => [region.canonicalName, region]))",
            "",
            "export const findRegion = (name: string): RegionDefinition | undefined =>",
            "  BY_NAME.get(name.trim())",
            "",
            "/**",
            " * Whether addresses in this region carry a city level between region and",
            " * district. Every province does; the metropolitan cities and Sejong do not.",
            " */",
            "export const regionHasCityLevel = (name: string): boolean =>",
            "  findRegion(name)?.hasCityLevel ?? false",
            "",
            "export const regionCenter = (name: string): { lat: number; lng: number } | undefined =>",
            "  findRegion(name)?.center",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args(argv)

    rendered = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != rendered:
            print(f"{TARGET} is out of date; run python etl/export_region_registry_ts.py")
            return 1
        print(f"{TARGET.name} is current")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
